services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: 'realworld_frontend'
    command: npm run dev
    restart: always
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - auth
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: 'realworld_api'
    command: npm run start
    restart: always
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo_api:27017/api_db
      - AUTH_URL=http://auth:3000/auth
    volumes:
      - ./api/src:/app/src
    depends_on:
      - mongo_api

  mongo_api:
    image: mongo:latest
    container_name: 'realworld_mongo_api'
    restart: always
    volumes:
      - mongo_api_db:/data/db

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: 'realworld_auth'
    command: npm run start
    restart: always
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo_auth:27017/auth_db
      - API_URL=http://api:3000/api
    volumes:
      - ./auth/src/:/app/src
    depends_on:
      - mongo_auth

  mongo_auth:
    image: mongo:latest
    container_name: 'realworld_mongo_auth'
    restart: always
    volumes:
      - mongo_auth_db:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: 'realworld_nginx'
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - auth
      - api

volumes:
  mongo_api_db:
    name: 'realworld_mongo_api_db'
  mongo_auth_db:
    name: 'realworld_mongo_auth_db'

networks:
  default:
    external: true
    name: realworld-network
